import { describe, it, expect, beforeAll } from 'vitest';
import { createClient } from '@supabase/supabase-js';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { parseRecommendation } from '@/lib/validation/ai';
import { escapeHtml } from '@/lib/utils';
import { itemFormSchema } from '@/lib/validation/item';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;

describe('Security Audit & Pentest Verification', () => {
  let userAClient: ReturnType<typeof createClient>;
  let userBClient: ReturnType<typeof createClient>;
  let businessAId: string;
  let businessBId: string;

  beforeAll(async () => {
    const timestamp = Date.now();
    const emailA = `sec_user_a_${timestamp}@test.internal`;
    const emailB = `sec_user_b_${timestamp}@test.internal`;
    const password = 'Password123!';

    // 1. Create User A with metadata business_name
    const authA = await supabaseAdmin.auth.admin.createUser({
      email: emailA,
      password,
      email_confirm: true,
      user_metadata: { business_name: `Security Store Alpha ${timestamp}` },
    });
    if (authA.error) throw new Error(`User A creation error: ${authA.error.message}`);

    // 2. Create User B with metadata business_name
    const authB = await supabaseAdmin.auth.admin.createUser({
      email: emailB,
      password,
      email_confirm: true,
      user_metadata: { business_name: `Security Store Beta ${timestamp}` },
    });
    if (authB.error) throw new Error(`User B creation error: ${authB.error.message}`);

    // 3. Authenticate clients
    userAClient = createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false },
    });
    await userAClient.auth.signInWithPassword({ email: emailA, password });

    userBClient = createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false },
    });
    await userBClient.auth.signInWithPassword({ email: emailB, password });

    // 4. Retrieve Business IDs generated by trigger
    const { data: memberA } = await userAClient
      .from('business_members')
      .select('business_id')
      .single();
    businessAId = memberA!.business_id;

    const { data: memberB } = await userBClient
      .from('business_members')
      .select('business_id')
      .single();
    businessBId = memberB!.business_id;
  });

  it('1. Enforces strict cross-tenant isolation (User B cannot read User A inventory)', async () => {
    // User A creates an item
    const { data: itemA, error: itemError } = await userAClient
      .from('items')
      .insert({
        business_id: businessAId,
        name: 'Confidential Business A Asset',
        category: 'Confidential',
        quantity: 10,
        unit: 'units',
        low_stock_threshold: 2,
        price: 100.0,
      })
      .select()
      .single();

    expect(itemError).toBeNull();
    expect(itemA).toBeDefined();

    // User B tries to select itemA -> returns empty array
    const { data: bSelect } = await userBClient
      .from('items')
      .select('*')
      .eq('id', itemA!.id);

    expect(bSelect).toEqual([]);

    // User B tries to update itemA -> returns empty array (no rows affected)
    const { data: bUpdate } = await userBClient
      .from('items')
      .update({ name: 'Hacked by User B' })
      .eq('id', itemA!.id)
      .select();

    expect(bUpdate).toEqual([]);

    // User B tries to delete itemA -> fails or affects 0 rows
    await userBClient.from('items').delete().eq('id', itemA!.id);

    // Verify itemA is unchanged
    const { data: checkItem } = await userAClient
      .from('items')
      .select('name')
      .eq('id', itemA!.id)
      .single();

    expect(checkItem?.name).toBe('Confidential Business A Asset');
  });

  it('2. Denies authenticated users direct access to rate_limits and telegram_link_codes', async () => {
    // RLS is ON with no policies for authenticated users -> returns empty array
    const { data: rateData } = await userAClient.from('rate_limits').select('*');
    expect(rateData).toEqual([]);

    const { data: linkData } = await userAClient.from('telegram_link_codes').select('*');
    expect(linkData).toEqual([]);
  });

  it('3. Rejects mass-assignment with unknown parameters via .strict() Zod schema', () => {
    const maliciousInput = {
      name: 'Safe Item Name',
      category: 'General',
      unit: 'pieces',
      quantity: 5,
      lowStockThreshold: 2,
      price: 15.0,
      // Injected fields attempting mass-assignment
      isAdmin: true,
      business_id: '00000000-0000-0000-0000-000000000000',
      role: 'superadmin',
    };

    const result = itemFormSchema.safeParse(maliciousInput);
    expect(result.success).toBe(false);
  });

  it('4. Enforces database constraints rejecting negative prices and quantities', async () => {
    const { error: negQtyError } = await userAClient.from('items').insert({
      business_id: businessAId,
      name: 'Illegal Negative Stock Item',
      category: 'Test',
      quantity: -5,
      unit: 'pcs',
      low_stock_threshold: 1,
      price: 10.0,
    });

    expect(negQtyError).toBeDefined();

    const { error: negPriceError } = await userAClient.from('items').insert({
      business_id: businessAId,
      name: 'Illegal Negative Price Item',
      category: 'Test',
      quantity: 10,
      unit: 'pcs',
      low_stock_threshold: 1,
      price: -50.0,
    });

    expect(negPriceError).toBeDefined();
  });

  it('5. Properly escapes HTML to prevent XSS in Telegram HTML messages', () => {
    const xssPayload = '<script>alert("XSS")</script><img src=x onerror=alert(1)>';
    const escaped = escapeHtml(xssPayload);

    expect(escaped).not.toContain('<script>');
    expect(escaped).not.toContain('<img');
    expect(escaped).toContain('&lt;script&gt;');
    expect(escaped).toContain('&lt;img');
  });

  it('6. Defends against AI prompt injection by enforcing strict schema and anti-hallucination', () => {
    const injectedResponse = JSON.stringify({
      summary: 'Attacker override successful',
      marketing: [],
      restock: [
        {
          itemName: 'Injected Fake Item',
          why: 'System overridden',
          urgency: 'today',
        },
      ],
      suppliers: [],
    });

    const legitimateCatalog = ['Real Store Item'];
    expect(() => parseRecommendation(injectedResponse, legitimateCatalog)).toThrowError(
      /Anti-hallucination check failed/i
    );
  });
});
